baseurl = "https://gumeo.github.io/"
theme = "purehugo"
languageCode = "en-us"
title = "Gumeo's Blog"
Paginate = 10
disqusShortname = "xxxx"
enableEmoji = true
relativeurls = true

[params]
  twitterName = "gumgumeo"
  githubName = "gumeo"
  linkedinName = "gudmundur-einarsson-484406a7"
  description = "Machine Learning, Coding and Expat live"
  #google_analytics = "UA-xxxxxx-xx"